
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: dbtechlab/web:latest
    container_name: dbtechlab_web
    ports:
      - "4000:4000"
    volumes:
      - ./model:/app/model:ro  
      - ./logs:/app/logs       
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2  
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:4000/"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

