name: CD

on:
  workflow_dispatch:   
  schedule:
    - cron: "0 6 * * *"   

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run container
        run: |
          docker run -d --rm \
            -p 4000:4000 \
            --name web \
            ${{ secrets.DOCKERHUB_USERNAME }}/dbtechlab-web:latest
          sleep 20

      - name: Functional test /predict
        run: |
          curl -s -X POST http://localhost:4000/predict \
            -H "Content-Type: application/json" \
            -d '{"instances":[{"mean radius":10.0}]}' | tee result.json
          grep -q "predictions" result.json

      - name: Stop container
        if: always()
        run: docker stop web

